# Generated by Django 4.1.7 on 2023-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imgApp", "0003_product_product_image_alter_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="product_image",),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
